/**
 * Module dependencies
 */

/**
 * Public node modules
 */

import {
  Request,
  Response,
}                 from 'express'
import log        from '../config/log'
import { Mysql }  from '../data-access/source/mysql/mysql-access'

/**
 * Service's parameter type which generated by a sql statement
 */
export interface Parameter {
  name        : string,       // parameter name
  type        : string,       // parameter type
  defaultValue: any,          // default value of parameter
  description : string,       // description of parameter
}

/**
 * Service's response type, which is return in json format
 */
export interface SQLResult {
  [name: string]: string,    // response's name and type
}

/**
 * Generate a sql with related fields
 * @param req
 * @param res
 */
export const sqlGenerate = (req: Request, res: Response) => {
  const { select, from, where, groupBy, orderBy, limit } = req.body
  if (!select) {
    res.send({ error: `select field can't be null` })
    return
  }
  if (!where) {
    res.send({ error: `where field can't be null` })
    return
  }
  if (!from) {
    res.send({ error: `from field can't be null` })
    return
  }
  let sql = 'select '
  sql += select.join(',')
  sql += ' from '
  sql += from.join(' ,')
  sql += ' where '
  sql += where.join(' ')
  if (groupBy && groupBy.length > 0) {
    sql += ' group by '
    sql += groupBy.join(' ,')
  }
  if (orderBy && orderBy.length > 0) {
    sql += ' order by '
    sql += orderBy.join(' ,')
  }
  if (limit) {
    try {
      parseInt(limit, 10)
    } catch (error) {
      res.send({ error: 'limit field must be numberical' })
    }
    sql += ' limit ' + limit
  }
  log.info('sqlGenerate', 'sql:\n%s', sql)
  res.send({ sql, error: null })

  // 处理输入输出
}

/**
 * Test a sql statement
 * @param req
 * @param res
 */
export const sqlTest = async (req: Request, res: Response) => {
  let sql: string = req.query.sql
  log.info(sql)
  const connection = await Mysql.getConnection()
  try {
    const result = await Mysql.query(sql, connection)
    res.send({ result })
  } catch (error) {
    res.send({ error })
  }
}
