export const MysqlDataType  = {
  'TINYINT'   : 'number',
  'SMALLINT'  : 'number',
  'MEDIUMINT' : 'number',
  'INT'       : 'number',
  'INTEGER'   : 'number',
  'BIGINT'    : 'number',
  'FLOAT'     : 'number',
  'DOUBLE'    : 'number',
  'DECIMAL'   : 'number',
  'DATE'      : 'string',
  'TIME'      : 'string',
  'YEAR'      : 'string',
  'DATETIME'  : 'string',
  'TIMESTAMP' : 'string',
  'CHAR'      : 'string',
  'VARCHAR'   : 'string',
  'TINYBLOB'  : 'string',
  'TINYTEXT'  : 'string',
  'BLOB'      : 'string',
  'TEXT'      : 'string',
  'MEDIUMBLOB': 'string',
  'MEDIUMTEXT': 'string',
  'LONGBLOB'  : 'string',
  'LONGTEXT'  : 'string',
}